#!/bin/bash

HERE=$( cd $( dirname $0 ); pwd )
BACKY=/usr/sbin/d9t-backy
DIFF=/usr/bin/diff
BACKUP=/tmp/backy_test_backup

export PYTHONPATH=$PYTHONPATH:$HERE

if [ ! -x $BACKY ]; then
    BACKY=./d9t-backy
fi

rm -r $BACKUP 2>/dev/null
mkdir $BACKUP


echo -n "Generating Test Data"
dd if=/dev/urandom of=$BACKUP/img_state1.img bs=1M count=20 2>/dev/null
echo -n "."
dd if=/dev/urandom of=$BACKUP/img_state2.img bs=1M count=20 2>/dev/null
echo -n "."
dd if=/dev/urandom of=$BACKUP/img_state3.img bs=1M count=20 2>/dev/null
echo " Done."


echo -n "Backing up img_state1.img. "
$BACKY -b $BACKUP/img_state1.img $BACKUP/backup > /dev/null
echo "Done."

echo -n "Restoring $BACKUP/img_state1.img from level 0. "
$BACKY -r $BACKUP/backup 0 $BACKUP/restore_state1.img > /dev/null
echo "Done."

echo -n "Diffing restore_state1.img against $BACKUP/img_state1.img. "
res=$($DIFF $BACKUP/restore_state1.img $BACKUP/img_state1.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

# cleanup
rm $BACKUP/restore_*




echo -n "Backing up img_state2.img. "
$BACKY -b $BACKUP/img_state2.img $BACKUP/backup > /dev/null
echo "Done."

echo -n "Restoring img_state2.img from level 0. "
$BACKY -r $BACKUP/backup 0 $BACKUP/restore_state2.img > /dev/null
echo "Done."

echo -n "Diffing restore_state2.img against img_state2.img. "
res=$($DIFF $BACKUP/restore_state2.img $BACKUP/img_state2.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

echo -n "Restoring $BACKUP/img_state1.img from level 1. "
$BACKY -r $BACKUP/backup 1 $BACKUP/restore_state1.img > /dev/null
echo "Done."

echo -n "Diffing restore_state1.img against $BACKUP/img_state1.img. "
res=$($DIFF $BACKUP/restore_state1.img $BACKUP/img_state1.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

# cleanup
rm $BACKUP/restore_*





echo -n "Backing up img_state2.img again. "
$BACKY -b $BACKUP/img_state2.img $BACKUP/backup > /dev/null
echo "Done."

echo -n "Restoring img_state2.img from level 0. "
$BACKY -r $BACKUP/backup 0 $BACKUP/restore_state2.img > /dev/null
echo "Done."

echo -n "Diffing restore_state2.img against img_state2.img. "
res=$($DIFF $BACKUP/restore_state2.img $BACKUP/img_state2.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

rm $BACKUP/restore_state2.img

echo -n "Restoring img_state2.img from level 1. "
$BACKY -r $BACKUP/backup 1 $BACKUP/restore_state2.img > /dev/null
echo "Done."

echo -n "Diffing restore_state2.img against img_state2.img. "
res=$($DIFF $BACKUP/restore_state2.img $BACKUP/img_state2.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

echo -n "Restoring $BACKUP/img_state1.img from level 2. "
$BACKY -r $BACKUP/backup 2 $BACKUP/restore_state1.img > /dev/null
echo "Done."

echo -n "Diffing restore_state1.img against $BACKUP/img_state1.img. "
res=$($DIFF $BACKUP/restore_state1.img $BACKUP/img_state1.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

# cleanup
rm $BACKUP/restore_*





echo -n "Backing up img_state3.img. "
$BACKY -b $BACKUP/img_state3.img $BACKUP/backup > /dev/null
echo "Done."

echo -n "Restoring img_state3.img from level 0. "
$BACKY -r $BACKUP/backup 0 $BACKUP/restore_state3.img > /dev/null
echo "Done."

echo -n "Diffing restore_state3.img against img_state3.img. "
res=$($DIFF $BACKUP/restore_state3.img $BACKUP/img_state3.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

echo -n "Restoring img_state2.img from level 1. "
$BACKY -r $BACKUP/backup 1 $BACKUP/restore_state2.img > /dev/null
echo "Done."

echo -n "Diffing restore_state2.img against img_state2.img. "
res=$($DIFF $BACKUP/restore_state2.img $BACKUP/img_state2.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

rm $BACKUP/restore_state2.img

echo -n "Restoring img_state2.img from level 2. "
$BACKY -r $BACKUP/backup 2 $BACKUP/restore_state2.img > /dev/null
echo "Done."

echo -n "Diffing restore_state2.img against img_state2.img. "
res=$($DIFF $BACKUP/restore_state2.img $BACKUP/img_state2.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

echo -n "Restoring $BACKUP/img_state1.img from level 3. "
$BACKY -r $BACKUP/backup 3 $BACKUP/restore_state1.img > /dev/null
echo "Done."

echo -n "Diffing restore_state1.img against $BACKUP/img_state1.img. "
res=$($DIFF $BACKUP/restore_state1.img $BACKUP/img_state1.img)
if [ "" == "$res" ]; then
    echo "Success."
else
    echo "ERROR: $res"
    exit 2
fi

# cleanup
rm -r $BACKUP



